version: '3'

services:
  api:
    build: ./api
    command: fresh
    volumes:
      - ./api:/go/src/api
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
